### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by DaltonFox** [DaltonFox/NeonSpace#1]
Setup initial game test code **finished**
Setup networking host code

NOTE: If the issue is solved put **finished** next to it in your edit comment so everyone knows

**Comment by Cheapsalsa** [comment]
work on client side game code

**Comment by Bencard** [comment]
To do list to be done by Tuesday (made by Nathaniel and Brandon)

Networking (at least for 2 people to connect for basic testing)

-Different colors (we think this works we just need to network to see multiple ships work)

basic combat
       hit detection
       HP
       (by Thursday energy)

Username / nickname input

Score board?

Art
   -Gravity wells with the art (by Thursday?)

Objects in space
    Debris - from ships
    Asteroids 

Remove the jank and trash

Scaling for when you zoom out/in/out/in/out

**Comment by Cheapsalsa** [comment]
I can remove the jank and trash / optimize the jank.

I'll also work on the scaling / zooming. I can attempt networking... Score board can be done using a data base on our server but this is not easy, I'll tackle basic network communications first. I will incorporate the nickname stuff and maybe chat with my network code as it is completed.

I assume someone who does the objects will have them interactable. Just use pygame circles for objects for now. Use pygame graphics for anything we don't have art for.

Hope gridlines look nice hehe.

Just get it done ;)

**Comment by Cheapsalsa** [comment]
If we are updating the world to have an round border I am increasing it to 12k x 12k

**Comment by katio174** [comment]
[Global New To-Do?]

- remove test-code
- Meteor library stuff
- re-arrange hud elements
- spot light / radar blips
- make light flicker and shut ship down under a certain a certain energy thresold
- planetary gravitation
- powerups
